services:
  clientemqtt:
    image: clientemqtt
    container_name: clientemqttmateo2
    environment:
      - TZ=America/Argentina/Buenos_Aires 
      - SERVIDOR=${SERVIDOR} #Se reemplazará por la env var SERVIDOR defineda en .env
      - TOPICO1=${TOPICO01}
      - TOPICO2=${TOPICO02}
    restart: unless-stopped